KAGGLE:
  dataset_name: taweilo/loan-approval-classification-data
  file_name: loan_data.csv

LOCAL:
  inital_file_name: raw_data.csv
  cleaned_file_name: cleaned_data.csv
  feature_engineered_file_name: feature_engineered_data.csv
  transformer_file_name: power_transformer.pkl